name: TrustEVM Contract CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:

jobs:
  documentation:
    name: Attach Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'false'

      - name: Attach Documentation
        run: cat .github/workflows/contract.md >> $GITHUB_STEP_SUMMARY

  build:
    runs-on: ubuntu-20.04
    name: TrustEVM Contract Build and Tests
    env:
      CC: gcc-10
      CXX: g++-10
      DCMAKE_BUILD_TYPE: 'Release'

    steps:
      - name: Authenticate
        id: auth
        uses: AntelopeIO/github-app-token-action@v1
        with:
          app_id: ${{ secrets.TRUSTEVM_CI_APP_ID }}
          private_key: ${{ secrets.TRUSTEVM_CI_APP_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ steps.auth.outputs.token }}

      - name: Download CDT
        uses: AntelopeIO/asset-artifact-download-action@v2
        with:
          owner: AntelopeIO
          repo: cdt
          target: 'v3.1.0'
          prereleases: false
          file: 'cdt_.*amd64.deb'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CDT
        run: sudo apt-get install -y ./cdt*.deb

      - name: Download Leap - dev binary
        uses: AntelopeIO/asset-artifact-download-action@v2
        with:
          owner: AntelopeIO
          repo: leap
          target: 'v3.1.3'
          prereleases: false
          file: 'leap-dev.*(x86_64|amd64).deb'
          container-package: experimental-binaries
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Leap
        run: sudo apt-get install -y ./leap*.deb

      - name: Build TrustEVM Contracts and Tests
        run: .github/workflows/build-contract.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contract.tar.gz
          path: contract.tar.gz
          if-no-files-found: error

      - name: Test TrustEVM Contract
        run: .github/workflows/test-contract.sh

      - name: Upload Test Metrics
        uses: actions/upload-artifact@v3
        with:
          name: test-results.xml
          path: test-results.xml
          if-no-files-found: error
