name: TrustEVM Contract CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: TrustEVM Contract Build
    runs-on: ubuntu-20.04
    env:
      CC: gcc-10
      CXX: g++-10

    steps:
      - name: Authenticate
        id: auth
        uses: AntelopeIO/github-app-token-action@v1
        with:
          app_id: ${{ secrets.TRUSTEVM_CI_APP_ID }}
          private_key: ${{ secrets.TRUSTEVM_CI_APP_KEY }}

      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
          token: ${{ steps.auth.outputs.token }}

      - name: Attach Documentation
        run: cat .github/workflows/contract.md >> $GITHUB_STEP_SUMMARY

      - name: Download CDT
        uses: AntelopeIO/asset-artifact-download-action@v2
        with:
          owner: AntelopeIO
          repo: cdt
          target: 'v3.1.0'
          prereleases: false
          file: 'cdt_.*amd64.deb'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install CDT
        run: sudo apt-get install -y ./cdt*.deb

      - name: Build TrustEVM Contract
        run: .github/workflows/build-contract.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contract.tar.gz
          path: contract.tar.gz
          if-no-files-found: error

      - name: Download Leap - dev binary
        uses: AntelopeIO/asset-artifact-download-action@v2
        with:
          owner: AntelopeIO
          repo: leap
          target: 'v3.1.3'
          prereleases: false
          file: 'leap-dev.*(x86_64|amd64).deb'
          container-package: experimental-binaries
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Leap
        run: sudo apt-get install -y ./leap*.deb

      - name: Build TrustEVM Contract Tests
        run: .github/workflows/build-contract-test.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contract-test.tar.gz
          path: contract-test.tar.gz
          if-no-files-found: error
