name: TrustEVM Node CI

on: [push, workflow_dispatch]

jobs:
  build:
    name: TrustEVM Node Build
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'true'

      - name: TrustEVM Node Build
        run: .github/workflows/node-build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build.tar.gz
          path: build.tar.gz
